name: ui-tests passage-ios-uitest-app
on:
  workflow_dispatch:
    inputs:
      passage_ios_branch_name:
        description: 'Branch name from the Passage iOS PR'
        required: true

jobs:
  ui-test-iOS:
    name: Build and UI Test iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Update the Podfile to use the branch version of the Passage pod
          sed -i.bak -e "s|pod 'Passage'|pod 'Passage', :git => 'https://github.com/passageidentity/passage-ios.git', :branch => '${{ github.event.inputs.passage_ios_branch_name }}'|" Podfile
          # Install the pods
          pod install
        shell: bash

      - name: Test iOS
        run: |
          xcodebuild clean build-for-testing test \
          -workspace 'passage-ios-uitest-app.xcworkspace' \
          -scheme 'passage-ios-uitest-app' \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          clean test | tee test_output.log | xcpretty --report junit --output junit.xml
      
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_output.log
  
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: junit.xml
  
      - name: Analyze Test Results
        if: failure()
        run: |
          echo "Tests failed. Analyzing results..."
          cat test_output.log
