name: ui-tests passage-ios-uitest-app
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ui-test-iOS-17:
    name: Build and UI Test iOS 17
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app

      - name: Test iOS 17.0
        run: xcodebuild clean test -scheme 'passage-ios-uitest-app' -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
